# Generated by Django 3.1.7 on 2021-04-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatType', models.CharField(max_length=7)),
                ('user1', models.ManyToManyField(related_name='user1', to='chats.User')),
                ('user2', models.ManyToManyField(related_name='user2', to='chats.User')),
            ],
        ),
    ]
